@url = http://127.0.0.1:3000/api
@json = Content-Type: application/json


###
GET {{url}}
{{json}}

### 注册
POST {{url}}/register
{{json}}

{
  "username":"user11",
  "password":"123"
}

### 获取所有用户
GET {{url}}/userlist
{{json}}